### Aufgabe 1

In [ ]:
array1 = ['python','PHP','java','C++']
print(array)

In [5]:
#capitalize the first letter
array2 = [ languages.capitalize() for languages in array]
print(array2)

['Python', 'Php', 'Java', 'C++']


In [7]:
#lowercase
array3 = [ languages.lower() for languages in array]
print(array3)

['python', 'php', 'java', 'c++']


In [10]:
#upper
array4 = [ languages.upper() for languages in array]
print(array4)

['PYTHON', 'PHP', 'JAVA', 'C++']


In [15]:
#swapcase
array5 = [ languages.swapcase() for languages in array]
print(array5)

['PYTHON', 'PHP', 'JAVA', 'c++']


In [16]:
#title case
array6 = [ languages.title() for languages in array]
print(array6)

['Python', 'Php', 'Java', 'C++']


### Aufgabe 2
Write a numpy program to create a structured array from given studen name,weight,class and their data types.

-Sort by class.

-Sort by age,if classes are equal.

In [15]:
import numpy as np
data_type = [('name', 'S15'), ('class', int), ('weight', float)]
students_details=[('alper',1,76.3),('deniz',3,39.5),('atakan',2,90.2),('dilanur',3,49.2)]
print(student_details)

[('deniz', 3, 39.5), ('dilanur', 3, 49.2), ('alper', 1, 76.3), ('atakan', 2, 90.2)]


In [16]:
# create a structured array
students = np.array(students_details, dtype=data_type)   
print("Original array:")
print(students)
print("Sort by weight")
print(np.sort(students, order='weight'))   
print("Sort by class, then weight if class are equal:")
print(np.sort(students, order=['class', 'weight']))

Original array:
[(b'alper', 1, 76.3) (b'deniz', 3, 39.5) (b'atakan', 2, 90.2)
 (b'dilanur', 3, 49.2)]
Sort by weight
[(b'deniz', 3, 39.5) (b'dilanur', 3, 49.2) (b'alper', 1, 76.3)
 (b'atakan', 2, 90.2)]
Sort by class, then weight if class are equal:
[(b'alper', 1, 76.3) (b'atakan', 2, 90.2) (b'deniz', 3, 39.5)
 (b'dilanur', 3, 49.2)]


### Aufgabe 3 
Write a numpy program to add a border (filled with 0's) to a given existing array.

In [17]:
import numpy as np
x = np.ones((3,3))
print("Original array:")
print(x)
print("0 on the border and 1 inside in the array")
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]
